language: node_js

notifications:
    email:
        recipents:
            - y1j2x34@qq.com
    on_success: change
    on_failure: always

node_js:
    - "8"
    - "9"
    - "10"
    - "11"
    - "12"

before_install:
  - node_version=$(node -v)
  - if [ ${node_version:1:2} = 10 ]; then npm install --save-dev natives@1.1.6; fi

install:
    - npm install


script:
    - npm run coverage
    - npm run coveralls
